travis:
  secure:
    BINSTAR_TOKEN: gJ7bQ494/kKj0lvs8Fc3c++DThzlxjUoheClJ45k8eU6XBifIGbUZ4caOeyaZIySwOYWASi/tMgWbvOANk+RkmT5rnOma1tRKWT+dcvy6D8p8D+xeNG55KBOQEys6+vYAeAu6jG9W8F0yU6mfSWh4Os1C74sPwHe1e7soSjSUOfF3z70iRvy3gJVnpaJx0SrDd+JaieGZA8xlcMG+N9H+dpjpJ3IaF1aF+1YLx4LrQwfb1hP5ZTn5do5i0+k0MZwkrMYAJMUa3IgAfnWvbO0xoziSOE2axVkrLOR2MwoPi5YJwILpweL/6Mg3lU1eoBTXuNxCiVoEAJ02g4PglNbJTM08exTrlpEJKllf2O46FHR3oWeUuuQ26h6xXrZBUe8aFYDXkPXCBheW3MSJY84JB3eoAAOiGfx6ulTayK0W/zCIQpmixF5Dv3sIxpcoyIHH3ejFwzIUHGPwsX5E+rFxKbKVSCKWz5c/wXP5WEZjEypvGiFyq0gBm9ahzg8DbQmCOOX7IkdV+NuqLRU8xdtFNiJpRUe3v/px7Fwti1OvKBG/DaLwpTnoSXIxCXuoMAUlbDO2qyIrdf7dvdalKb9WCjbCcle7BX0wWVxNW78D6UruBfkYoEAkc5WngXdHjvaHq/SAwCdOjTA074DEjbxl8BuFLnKaDDv5lfPOQLQESg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
